version: '3.7'
services:
  apache:
    build: ops/apache
    container_name: app_apache
    depends_on:
      - php
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - './ops/apache/config/vhosts:/etc/apache2/sites-enabled'
      - './back:/home/wwwroot/symfony'

  php:
    build: ops/php
    container_name: app_php
    depends_on:
      - postgres
    volumes:
      - './back:/home/wwwroot/symfony'
    ports:
      - '9090:9090'

  node:
    build:
      context: ./
      dockerfile: ./ops/node/Dockerfile
    container_name: app_node
    depends_on:
      - apache
      - postgres
    working_dir: /app
    ports:
      - '3000:8080'
    volumes:
      - './front:/app'
      - '/app/node_modules/'

  pgweb:
    container_name: app_pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://root:root@postgres:5432/app?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: app_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app

  s3:
    image: minio/minio:latest
    container_name: app_s3
    hostname: s3
    command:
      - server
      - /data
      - --address
      - ":7000"
      - --console-address
      - ":7001"
    env_file: ./ops/minio/.env
    ports:
      - 7000:7000
      - 7001:7001
    volumes:
      - s3-data:/data

volumes:
  postgres:
  s3-data: